/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cardapio;

import javax.swing.JOptionPane;

/**
 *
 * @author laila
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Lanches = new javax.swing.JButton();
        Almoço = new javax.swing.JButton();
        Bebidas = new javax.swing.JButton();
        Jantar = new javax.swing.JButton();
        Sobremesas = new javax.swing.JButton();
        Cafe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Voltar = new javax.swing.JMenu();
        Volta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));

        Lanches.setBackground(new java.awt.Color(255, 255, 255));
        Lanches.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardapio/lanche.png"))); // NOI18N
        Lanches.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        Lanches.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lanches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LanchesActionPerformed(evt);
            }
        });

        Almoço.setBackground(new java.awt.Color(255, 255, 255));
        Almoço.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardapio/almoco.png"))); // NOI18N
        Almoço.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        Almoço.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Almoço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlmoçoActionPerformed(evt);
            }
        });

        Bebidas.setBackground(new java.awt.Color(255, 255, 255));
        Bebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardapio/bebidas.png"))); // NOI18N
        Bebidas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        Bebidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BebidasActionPerformed(evt);
            }
        });

        Jantar.setBackground(new java.awt.Color(255, 255, 255));
        Jantar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardapio/jantar.png"))); // NOI18N
        Jantar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        Jantar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jantar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JantarActionPerformed(evt);
            }
        });

        Sobremesas.setBackground(new java.awt.Color(255, 255, 255));
        Sobremesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardapio/sobremesa.png"))); // NOI18N
        Sobremesas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        Sobremesas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sobremesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobremesasActionPerformed(evt);
            }
        });

        Cafe.setBackground(new java.awt.Color(255, 255, 255));
        Cafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardapio/cafe.png"))); // NOI18N
        Cafe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        Cafe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cafe.setMaximumSize(new java.awt.Dimension(105, 2));
        Cafe.setPreferredSize(new java.awt.Dimension(103, 59));
        Cafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CafeActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 153, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardapio/logo.png"))); // NOI18N
        jLabel6.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jRadioButton1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jRadioButton1.setText("Cadastrar itens");
        jRadioButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jRadioButton2.setText("Consultar vendas");
        jRadioButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Cafe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(Bebidas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(Jantar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                        .addGap(88, 88, 88)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Sobremesas, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(Lanches, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(Almoço, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Almoço, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cafe, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Bebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lanches, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Sobremesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jantar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Voltar.setBackground(new java.awt.Color(255, 255, 255));
        Voltar.setText("Opções");
        Voltar.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N

        Volta.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        Volta.setText("Voltar");
        Volta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltaActionPerformed(evt);
            }
        });
        Voltar.add(Volta);

        jMenuBar1.add(Voltar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltaActionPerformed
        if(evt.getSource() == Volta){
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_VoltaActionPerformed

    private void LanchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LanchesActionPerformed
        if(evt.getSource() == Lanches){
            if(jRadioButton1.isSelected()){
                new Lanche().setVisible(true);
                this.dispose();            
            }else
            if(jRadioButton2.isSelected()){
                new ConsLanche().setVisible(true);
                this.dispose();
            }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um item!");
            }
        }
    }//GEN-LAST:event_LanchesActionPerformed

    private void AlmoçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlmoçoActionPerformed

        if(evt.getSource() == Almoço){
            if(jRadioButton1.isSelected()){
                new Almoço().setVisible(true);
                this.dispose();            
            }else
            if(jRadioButton2.isSelected()){
                new ConsAlmoço().setVisible(true);
                this.dispose();
            }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um item!");
            }
        }
    }//GEN-LAST:event_AlmoçoActionPerformed

    private void BebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BebidasActionPerformed
        if(evt.getSource() == Bebidas){
            if(jRadioButton1.isSelected()){
                new Bebidas().setVisible(true);
                this.dispose();            
            }else
            if(jRadioButton2.isSelected()){
                new ConsBebidas().setVisible(true);
                this.dispose();
            }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um item!");
            }
        }
    }//GEN-LAST:event_BebidasActionPerformed

    private void JantarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JantarActionPerformed
        if(evt.getSource() == Jantar){
            if(jRadioButton1.isSelected()){
                new Jantar().setVisible(true);
                this.dispose();            
            }else
            if(jRadioButton2.isSelected()){
                new ConsJantar().setVisible(true);
                this.dispose();
            }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um item!");
            }
        }
    }//GEN-LAST:event_JantarActionPerformed

    private void SobremesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobremesasActionPerformed
        if(evt.getSource() == Sobremesas){
            if(jRadioButton1.isSelected()){
                new Sobremesa().setVisible(true);
                this.dispose();            
            }else
            if(jRadioButton2.isSelected()){
                new ConsSobremesa().setVisible(true);
                this.dispose();
            }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um item!");
            }
        }
    }//GEN-LAST:event_SobremesasActionPerformed

    private void CafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CafeActionPerformed
        if(evt.getSource() == Cafe){
            if(jRadioButton1.isSelected()){
                new Cafe().setVisible(true);
                this.dispose();            
            }else
            if(jRadioButton2.isSelected()){
                new ConsCafe().setVisible(true);
                this.dispose();
            }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um item!");
            }
        }
    }//GEN-LAST:event_CafeActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Almoço;
    private javax.swing.JButton Bebidas;
    private javax.swing.JButton Cafe;
    private javax.swing.JButton Jantar;
    private javax.swing.JButton Lanches;
    private javax.swing.JButton Sobremesas;
    private javax.swing.JMenuItem Volta;
    private javax.swing.JMenu Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
